#!/usr/bin/env bash
#BSUB -G ustruct
#BSUB -q pbatch
#BSUB -nnodes 1
#BSUB -W 12:00


jsrun -r 1 python main.py --dim 1 --model RCAN --scale 1 --save toy_2source --loss "1*L1" \
    --n_resgroups 10 --n_resblocks 20 --n_feats 64 --resume -1 \
    --dir_data ~/data/toy_spectrum/2source --data_train toy_spectrum --data_test toy_spectrum \
    --save_results --print_model --patch_size 384 --n_GPUs 4 \
    --n_colors 2 --n_colors_out 1 --no_augment --data_range '1-6388/6389-6420' \
    --batch_size 256 --n_threads 1

#--resume -1

#--pre_train ../experiment/model/RCAN_BIX2.pt \
